name: broken-link-checker
on:
  schedule:
    - cron: '59 23 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "bs4"
          python -m pip install "requests"
          python -m pip install "pandas"
          python -m pip install "datetime"
          python -m pip install "ultimate-sitemap-parser"
          
      - name: execute broken link script
        env: 
          GIT_TOKEN: ${{ secrets.SECRET_GIT_TOKEN }}
        run: |
          python broken_link_checker_final.py
